version: '3.6'
services:
  sponsorblockcast:
    image: nixuu/sponsorblockcast:latest
    network_mode: host
    environment:
      SBCPOLLINTERVAL: 1
      SBCSCANINTERVAL: 300
      SBCCATEGORIES: sponsor
      SBCDIR: /tmp/sponsorblockcast
    cap_add: 
      - NET_ADMIN
    restart: always
